spring:
  application:
    name: jooq-demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: root
    url: jdbc:mysql://118.25.41.246:3306/halodb?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
